Rewrote hooks to loop through changed lockfiles

diff --git a/FreeCAD_Automation/hooks/post-commit b/FreeCAD_Automation/hooks/post-commit
--- a/FreeCAD_Automation/hooks/post-commit
+++ b/FreeCAD_Automation/hooks/post-commit
@@ -26,17 +26,27 @@ fi
 #                                   Set Readonly / Writable
 # ==============================================================================================
 if [ "$REQUIRE_LOCKS" == "1" ]; then
-    for FCStd_file in $(git diff-tree --no-commit-id --name-only -r HEAD | grep -i '\.fcstd$'); do
-        FCSTD_FILE_HAS_VALID_LOCK=$(FCStd_file_has_valid_lock "$FCStd_file") || continue
+    CURRENT_USER=$(git config --get user.name) || {
+        echo "Error: git config user.name not set!" >&2
+        exit $FAIL
+    }
 
-        if [ "$FCSTD_FILE_HAS_VALID_LOCK" == "0" ]; then
-            # User doesn't have lock, set .FCStd file to readonly
-            make_readonly "$FCStd_file"
-            echo "DEBUG: set '$FCStd_file' readonly." >&2
-        else
+    CURRENT_LOCKS=$(git lfs locks | awk '$2 == "'$CURRENT_USER'" {print $3}') || {
+        echo "Error: failed to list of active lock info." >&2
+        exit $FAIL
+    }
+
+    for lockfile in $(git diff-tree --no-commit-id --name-only -r HEAD | grep -i '\.lockfile$'); do
+        FCStd_file_path=$(get_FCStd_file_from_lockfile "$lockfile") || continue
+
+        if echo "$CURRENT_LOCKS" | grep -q "$lockfile"; then
             # User has lock, set .FCStd file to writable
-            make_writable "$FCStd_file"
-            echo "DEBUG: set '$FCStd_file' writable." >&2
+            make_writable "$FCStd_file_path"
+            echo "DEBUG: set '$FCStd_file_path' writable." >&2
+        else
+            # User doesn't have lock, set .FCStd file to readonly
+            make_readonly "$FCStd_file_path"
+            echo "DEBUG: set '$FCStd_file_path' readonly." >&2
         fi
     done
 fi
diff --git a/FreeCAD_Automation/hooks/post-rewrite b/FreeCAD_Automation/hooks/post-rewrite
--- a/FreeCAD_Automation/hooks/post-rewrite
+++ b/FreeCAD_Automation/hooks/post-rewrite
@@ -25,53 +25,48 @@ echo "DEBUG: Pulled lfs files" >&2
 # ==============================================================================================
 #                         Update .FCStd files with uncompressed files
 # ==============================================================================================
-# Get all tracked .FCStd files (case insensitive)
-TRACKED_FCSTD_FILES=$(git ls-files | grep -i '\.fcstd$')
+if [ "$REQUIRE_LOCKS" == "1" ]; then
+    CURRENT_USER=$(git config --get user.name) || {
+        echo "Error: git config user.name not set!" >&2
+        exit $FAIL
+    }
+
+    CURRENT_LOCKS=$(git lfs locks | awk '$2 == "'$CURRENT_USER'" {print $3}') || {
+        echo "Error: failed to list of active lock info." >&2
+        exit $FAIL
+    }
+fi
 
 echo "DEBUG: diffing <remote sha1>='ORIG_HEAD'..'HEAD'=<local sha1>" >&2
 changed_files=$(git diff --name-only ORIG_HEAD..HEAD)
 
-echo "DEBUG: file changes: '$changed_files'" >&2
+# Get changed .lockfiles
+changed_lockfiles=$(echo "$changed_files" | grep -i '\.lockfile$')
 
-echo -e "\nDEBUG: checking '$(echo $TRACKED_FCSTD_FILES | xargs)' for changes..." >&2
+echo -e "\nDEBUG: checking changed lockfiles: '$(echo $changed_lockfiles | xargs)'" >&2
 
-for FCStd_file in $TRACKED_FCSTD_FILES; do
-    echo -e "\nDEBUG: checking '$FCStd_file'...." >&2
+for lockfile in $changed_lockfiles; do
+    echo -e "\nDEBUG: checking '$lockfile'...." >&2
 
-    # Get the uncompressed directory path for this .FCStd file
-    FCStd_dir_path=$(get_FCStd_dir "$FCStd_file") || {
-        echo "Error: Failed to get directory path for '$FCStd_file', skipping..." >&2
+    FCStd_file_path=$(get_FCStd_file_from_lockfile "$lockfile") || continue
+
+    echo "DEBUG: Detected changes, reloading '$FCStd_file_path'...." >&2
+
+    # Import data to FCStd file
+    "$PYTHON_PATH" "$FCStdFileTool" --SILENT --CONFIG-FILE --import "$FCStd_file_path" || {
+        echo "Error: Failed to import $FCStd_file_path, skipping..." >&2
         continue
     }
 
-    echo "DEBUG: Found dir '$FCStd_dir_path'" >&2
-
-    # Check if this directory has changes in the push
-    if echo "$changed_files" | grep -q "^$FCStd_dir_path/"; then
-        echo "DEBUG: Detected changes, reloading '$FCStd_file'...." >&2
-
-        # Import data to FCStd file
-        "$PYTHON_PATH" "$FCStdFileTool" --SILENT --CONFIG-FILE --import "$FCStd_file" || {
-            echo "Error: Failed to import $FCStd_file, skipping..." >&2
-            continue
-        }
-    else
-        echo "DEBUG: No changes found" >&2
-        :
-    fi
-
     if [ "$REQUIRE_LOCKS" == "1" ]; then
-        # Check if user has valid lock
-        FCSTD_FILE_HAS_VALID_LOCK=$(FCStd_file_has_valid_lock "$FCStd_file") || continue
-
-        if [ "$FCSTD_FILE_HAS_VALID_LOCK" == "0" ]; then
-            # User doesn't have lock, set .FCStd file to readonly
-            make_readonly "$FCStd_file"
-            echo "DEBUG: set '$FCStd_file' readonly." >&2
-        else
+        if echo "$CURRENT_LOCKS" | grep -q "$lockfile"; then
             # User has lock, set .FCStd file to writable
-            make_writable "$FCStd_file"
-            echo "DEBUG: set '$FCStd_file' writable." >&2
+            make_writable "$FCStd_file_path"
+            echo "DEBUG: set '$FCStd_file_path' writable." >&2
+        else
+            # User doesn't have lock, set .FCStd file to readonly
+            make_readonly "$FCStd_file_path"
+            echo "DEBUG: set '$FCStd_file_path' readonly." >&2
         fi
     fi
 done
diff --git a/FreeCAD_Automation/hooks/pre-commit b/FreeCAD_Automation/hooks/pre-commit
--- a/FreeCAD_Automation/hooks/pre-commit
+++ b/FreeCAD_Automation/hooks/pre-commit
@@ -14,22 +14,32 @@ source "$FUNCTIONS_FILE"
 # ==============================================================================================
 #                         Check if user allowed to modify .FCStd files
 # ==============================================================================================
-# Get staged .FCStd files
-STAGED_FCSTD_FILES=$(git diff --cached --name-only | grep -i '\.fcstd$')
-echo -e "\nDEBUG: checking '$(echo $STAGED_FCSTD_FILES | xargs)' for valid locks..." >&2
-
-for FCStd_file in $STAGED_FCSTD_FILES; do
-    echo -e "\nDEBUG: checking '$FCStd_file'...." >&2
-
-    FCSTD_FILE_HAS_VALID_LOCK=$(FCStd_file_has_valid_lock "$FCStd_file") || exit $FAIL
-    
-    if [ $FCSTD_FILE_HAS_VALID_LOCK == 0 ]; then
-        echo "ERROR: User doesn't have lock for '$FCStd_file'... Aborting commit operation..." >&2
+if [ "$REQUIRE_LOCKS" == "1" ]; then
+    CURRENT_USER=$(git config --get user.name) || {
+        echo "Error: git config user.name not set!" >&2
         exit $FAIL
-    else
-        echo "DEBUG: valid lock found" >&2
-        :
-    fi
-done
+    }
+
+    CURRENT_LOCKS=$(git lfs locks | awk '$2 == "'$CURRENT_USER'" {print $3}') || {
+        echo "Error: failed to list of active lock info." >&2
+        exit $FAIL
+    }
+
+    # Get staged .lockfiles
+    STAGED_LOCKFILES=$(git diff --cached --name-only | grep -i '\.lockfile$')
+    echo -e "\nDEBUG: checking staged lockfiles for valid locks..." >&2
+
+    for lockfile in $STAGED_LOCKFILES; do
+        echo -e "\nDEBUG: checking '$lockfile'...." >&2
+
+        if echo "$CURRENT_LOCKS" | grep -q "$lockfile"; then
+            echo "DEBUG: valid lock found for '$lockfile'" >&2
+            :
+        else
+            echo "ERROR: User doesn't have lock for '$lockfile'... Aborting commit operation..." >&2
+            exit $FAIL
+        fi
+    done
+fi
 
 exit $SUCCESS
diff --git a/FreeCAD_Automation/hooks/pre-push b/FreeCAD_Automation/hooks/pre-push
--- a/FreeCAD_Automation/hooks/pre-push
+++ b/FreeCAD_Automation/hooks/pre-push
@@ -40,46 +40,38 @@ source "$FUNCTIONS_FILE"
 # ==============================================================================================
 echo "DEBUG: args='$@'" >&2
 
-# Get all tracked .FCStd files (case insensitive)
-TRACKED_FCSTD_FILES=$(git ls-files | grep -i '\.fcstd$')
-
-echo "DEBUG: diffing <remote sha1>='$remote_sha'..'$local_sha'=<local sha1>" >&2
-changed_files=$(git diff --name-only $remote_sha..$local_sha)
-
-echo "DEBUG: file changes: '$changed_files'" >&2
-
-echo -e "\nDEBUG: checking '$(echo $TRACKED_FCSTD_FILES | xargs)' for matches" >&2
-
-for FCStd_file in $TRACKED_FCSTD_FILES; do
-    echo -e "\nDEBUG: checking '$FCStd_file'...." >&2
-
-    # Get the uncompressed directory path for this .FCStd file
-    FCStd_dir_path=$(get_FCStd_dir "$FCStd_file") || {
-        echo "Error: Failed to get directory path for '$FCStd_file'" >&2
+if [ "$REQUIRE_LOCKS" == "1" ]; then
+    CURRENT_USER=$(git config --get user.name) || {
+        echo "Error: git config user.name not set!" >&2
         exit $FAIL
     }
 
-    echo "DEBUG: Found dir '$FCStd_dir_path'" >&2
+    CURRENT_LOCKS=$(git lfs locks | awk '$2 == "'$CURRENT_USER'" {print $3}') || {
+        echo "Error: failed to list of active lock info." >&2
+        exit $FAIL
+    }
 
-    # Check if this directory has changes in the push
-    if echo "$changed_files" | grep -q "^$FCStd_dir_path/"; then
-        # Directory has changes, check lock for the .FCStd file
-        FCSTD_FILE_HAS_VALID_LOCK=$(FCStd_file_has_valid_lock "$FCStd_file") || exit $FAIL
-        
-        echo "DEBUG: Found changes in '$FCStd_file''s commits" >&2
+    echo "DEBUG: diffing <remote sha1>='$remote_sha'..'$local_sha'=<local sha1>" >&2
+    changed_files=$(git diff --name-only $remote_sha..$local_sha)
 
-        if [ $FCSTD_FILE_HAS_VALID_LOCK == 0 ]; then
-            echo "ERROR: User doesn't have lock for '$FCStd_file'... Aborting push operation..." >&2
-            exit $FAIL
-        else
-            echo "DEBUG: User has valid lock" >&2
+    echo "DEBUG: file changes: '$changed_files'" >&2
+
+    # Get changed .lockfiles
+    changed_lockfiles=$(echo "$changed_files" | grep -i '\.lockfile$')
+
+    echo -e "\nDEBUG: checking changed lockfiles for valid locks..." >&2
+
+    for lockfile in $changed_lockfiles; do
+        echo -e "\nDEBUG: checking '$lockfile'...." >&2
+
+        if echo "$CURRENT_LOCKS" | grep -q "$lockfile"; then
+            echo "DEBUG: User has valid lock for '$lockfile'" >&2
             :
+        else
+            echo "ERROR: User doesn't have lock for '$lockfile'... Aborting push operation..." >&2
+            exit $FAIL
         fi
-    else
-        echo "DEBUG: No changes found" >&2
-        :
-    fi
-
-done
+    done
+fi
 
 exit $SUCCESS
