Added errors to ensure vars dependent on config file are present

diff --git a/FreeCAD_Automation/hooks/post-merge b/FreeCAD_Automation/hooks/post-merge
--- a/FreeCAD_Automation/hooks/post-merge
+++ b/FreeCAD_Automation/hooks/post-merge
@@ -16,6 +16,11 @@ git lfs post-merge "$@"
 FUNCTIONS_FILE="FreeCAD_Automation/utils.sh"
 source "$FUNCTIONS_FILE"
 
+if [ -z "$PYTHON_PATH" ] || [ -z "$REQUIRE_LOCKS" ]; then
+    echo "Config file missing or invalid; cannot proceed." >&2
+    exit $FAIL
+fi
+
 # ==============================================================================================
 #                         Update .FCStd files with uncompressed files
 # ==============================================================================================
