post-commit now updates readonly/writable

diff --git a/FreeCAD_Automation/hooks/post-commit b/FreeCAD_Automation/hooks/post-commit
--- a/FreeCAD_Automation/hooks/post-commit
+++ b/FreeCAD_Automation/hooks/post-commit
@@ -1,5 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 echo "DEBUG: post-commit hook trap-card triggered!" >&2
+. ../utils.sh
 # ==============================================================================================
 #                                         GIT LFS Hooks
 # ==============================================================================================
@@ -7,6 +8,37 @@ command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configure
 
 git lfs post-commit "$@"
 # ==============================================================================================
-#                                         CUSTOM LOGIC
+#                                 Verify and Retrieve Dependencies
 # ==============================================================================================
+# Ensure working dir is the root of the repo
+# GIT_ROOT=$(git rev-parse --show-toplevel)
+# cd "$GIT_ROOT"
+
+# Import code used in this script
+FUNCTIONS_FILE="FreeCAD_Automation/utils.sh"
+source "$FUNCTIONS_FILE"
+
+if [ -z "$REQUIRE_LOCKS" ]; then
+    echo "Config file missing or invalid; cannot proceed." >&2
+    exit $FAIL
+fi
+
+# ==============================================================================================
+#                                   Set Readonly / Writable
+# ==============================================================================================
+if [ "$REQUIRE_LOCKS" == "1" ]; then
+    for FCStd_file in $(git diff-tree --no-commit-id --name-only -r HEAD | grep -i '\.fcstd$'); do
+        FCSTD_FILE_HAS_VALID_LOCK=$(FCStd_file_has_valid_lock "$FCStd_file") || continue
+
+        if [ "$FCSTD_FILE_HAS_VALID_LOCK" == "0" ]; then
+            # User doesn't have lock, set .FCStd file to readonly
+            make_readonly "$FCStd_file"
+            echo "DEBUG: set '$FCStd_file' readonly." >&2
+        else
+            # User has lock, set .FCStd file to writable
+            make_writable "$FCStd_file"
+            echo "DEBUG: set '$FCStd_file' writable." >&2
+        fi
+    done
+fi
 exit $SUCCESS
