Adjusted formatting

diff --git a/FreeCAD_Automation/hooks/pre-push b/FreeCAD_Automation/hooks/pre-push
--- a/FreeCAD_Automation/hooks/pre-push
+++ b/FreeCAD_Automation/hooks/pre-push
@@ -43,10 +43,15 @@ echo "DEBUG: args='$@'" >&2
 # Get all tracked .FCStd files (case insensitive)
 TRACKED_FCSTD_FILES=$(git ls-files | grep -i '\.fcstd$') 
 
-echo -e "DEBUG: checking '$(echo $TRACKED_FCSTD_FILES | xargs)'\n" >&2
+echo "DEBUG: diffing <remote sha1>='$remote_sha'..'$local_sha'=<local sha1>" >&2
+changed_files=$(git diff --name-only $remote_sha..$local_sha)
+
+echo "DEBUG: file changes: '$changed_files'" >&2
+
+echo -e "\nDEBUG: checking '$(echo $TRACKED_FCSTD_FILES | xargs)' for matches" >&2
 
 for FCStd_file in $TRACKED_FCSTD_FILES; do
-    echo "DEBUG: checking '$FCStd_file'" >&2
+    echo -e "\nDEBUG: checking '$FCStd_file'" >&2
 
     # Get the uncompressed directory path for this .FCStd file
     FCStd_dir_path=$(get_FCStd_dir "$FCStd_file") || {
@@ -56,17 +61,15 @@ for FCStd_file in $TRACKED_FCSTD_FILES; do
 
     echo "DEBUG: Found dir '$FCStd_dir_path'" >&2
 
-    echo "DEBUG: diffing <remote sha1>='$remote_sha'..'$local_sha'=<local sha1>" >&2
-
     # Check if this directory has changes in the push
-    if git diff --name-only $remote_sha..$local_sha | grep -q "^$FCStd_dir_path/"; then
+    if echo "$changed_files" | grep -q "^$FCStd_dir_path/"; then
         # Directory has changes, check lock for the .FCStd file
         FCSTD_FILE_HAS_VALID_LOCK=$(FCStd_file_has_valid_lock "$FCStd_file") || exit $FAIL
         
         echo "DEBUG: Found changes in '$FCStd_file''s commits" >&2
 
         if [ $FCSTD_FILE_HAS_VALID_LOCK == 0 ]; then
-            echo "ERROR: User doesn't have lock for '$FCStd_file'... Aborting commit operation..." >&2
+            echo "ERROR: User doesn't have lock for '$FCStd_file'... Aborting push operation..." >&2
             exit $FAIL
         fi
     fi
