Reworked clean filter to require a flag to export, otherwise it is disabled. Removed git stat as a result

diff --git a/FreeCAD_Automation/hooks/pre-commit b/FreeCAD_Automation/hooks/pre-commit
--- a/FreeCAD_Automation/hooks/pre-commit
+++ b/FreeCAD_Automation/hooks/pre-commit
@@ -21,6 +21,20 @@ if [ "$REQUIRE_LOCKS" == "$TRUE" ]; then
         exit $FAIL
     }
 
+    # Get staged `.FCStd` files
+    # Diff Filter => (A)dded / (C)opied / (D)eleted / (M)odified / (R)enamed / (T)ype changed / (U)nmerged / (X) unknown / (B)roken pairing
+    STAGED_FCSTD_FILES=$(git diff-index --cached --name-only --diff-filter=CDMRTUXB HEAD | grep -i '\.fcstd$')
+    echo -e "\nDEBUG: checking staged FCStd files: '$(echo $STAGED_FCSTD_FILES | xargs)'" >&2
+
+    for FCStd_file_path in $STAGED_FCSTD_FILES; do
+        echo -e "\nDEBUG: checking '$FCStd_file_path'...." >&2
+
+        if [ -s "$FCStd_file_path" ]; then
+            echo "ERROR: $FCStd_file_path is not empty, export it using \`git fadd\` or clear it using \`git fcmod\`" >&2
+            exit $FAIL
+        fi
+    done
+
     # Get staged `.changefile`s
     # Diff Filter => (A)dded / (C)opied / (D)eleted / (M)odified / (R)enamed / (T)ype changed / (U)nmerged / (X) unknown / (B)roken pairing
     STAGED_CHANGEFILES=$(git diff-index --cached --name-only --diff-filter=CDMRTUXB HEAD | grep -i '\.changefile$')
