More mature fix for infinite GitCAD recursion

diff --git a/FreeCAD_Automation/git b/FreeCAD_Automation/git
--- a/FreeCAD_Automation/git
+++ b/FreeCAD_Automation/git
@@ -20,7 +20,7 @@ if [ -z "$REAL_GIT" ]; then
 fi
 
 if [ "$REAL_GIT" = "$0" ]; then
-  echo "Error, infinite recursion detected: activate.sh or something else set REAL_GIT environment variable to this wrapper script instead of the real git executable" >&2
+  echo "Error, infinite recursion detected: activate.sh or something else set REAL_GIT environment variable to this wrapper script instead of the real git executable." >&2
   exit $FAIL
 fi
 
