Added note on pwd for git aliases, made error print format consistent

diff --git a/FreeCAD_Automation/git b/FreeCAD_Automation/git
--- a/FreeCAD_Automation/git
+++ b/FreeCAD_Automation/git
@@ -21,7 +21,7 @@ case $1 in
     
     # Get GIT_PREFIX (subdir the user is CDed into)
     GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
-      echo "ERROR: Current Directory is not a git repository" >&2
+      echo "Error: Current Directory is not a git repository" >&2
       exit 1 # 1=$FAIL
     }
     
diff --git a/FreeCAD_Automation/hooks/post-commit b/FreeCAD_Automation/hooks/post-commit
--- a/FreeCAD_Automation/hooks/post-commit
+++ b/FreeCAD_Automation/hooks/post-commit
@@ -14,7 +14,7 @@ FUNCTIONS_FILE="FreeCAD_Automation/utils.sh"
 source "$FUNCTIONS_FILE"
 
 if [ -z "$REQUIRE_LOCKS" ]; then
-    echo "Config file missing or invalid; cannot proceed." >&2
+    echo "Error: Config file missing or invalid; cannot proceed." >&2
     exit $FAIL
 fi
 
diff --git a/FreeCAD_Automation/hooks/post-merge b/FreeCAD_Automation/hooks/post-merge
--- a/FreeCAD_Automation/hooks/post-merge
+++ b/FreeCAD_Automation/hooks/post-merge
@@ -20,7 +20,7 @@ FUNCTIONS_FILE="FreeCAD_Automation/utils.sh"
 source "$FUNCTIONS_FILE"
 
 if [ -z "$PYTHON_PATH" ] || [ -z "$REQUIRE_LOCKS" ]; then
-    echo "Config file missing or invalid; cannot proceed." >&2
+    echo "Error: Config file missing or invalid; cannot proceed." >&2
     exit $FAIL
 fi
 
diff --git a/FreeCAD_Automation/hooks/pre-commit b/FreeCAD_Automation/hooks/pre-commit
--- a/FreeCAD_Automation/hooks/pre-commit
+++ b/FreeCAD_Automation/hooks/pre-commit
@@ -21,7 +21,7 @@ for FCStd_file_path in $STAGED_FCSTD_FILES; do
     # echo -e "\nDEBUG: checking '$FCStd_file_path'...." >&2
 
     if [ -s "$FCStd_file_path" ]; then
-        echo "ERROR: $FCStd_file_path is not empty, export it using \`git fadd\` or clear it using \`git fcmod\`" >&2
+        echo "Error: $FCStd_file_path is not empty, export it using \`git fadd\` or clear it using \`git fcmod\`" >&2
         exit $FAIL
     fi
 done
@@ -56,7 +56,7 @@ if [ "$REQUIRE_LOCKS" == "$TRUE" ]; then
             # echo "DEBUG: valid lock found for '$lockfile'" >&2
             :
         else
-            echo "ERROR: User doesn't have lock for '$lockfile'... Aborting commit operation..." >&2
+            echo "Error: User doesn't have lock for '$lockfile'... Aborting commit operation..." >&2
             exit $FAIL
         fi
     done
diff --git a/FreeCAD_Automation/hooks/pre-push b/FreeCAD_Automation/hooks/pre-push
--- a/FreeCAD_Automation/hooks/pre-push
+++ b/FreeCAD_Automation/hooks/pre-push
@@ -71,7 +71,7 @@ if [ "$REQUIRE_LOCKS" == "$TRUE" ]; then
             # echo "DEBUG: User has valid lock for '$lockfile'" >&2
             :
         else
-            echo "ERROR: User doesn't have lock for '$lockfile'... Aborting push operation..." >&2
+            echo "Error: User doesn't have lock for '$lockfile'... Aborting push operation..." >&2
             exit $FAIL
         fi
     done
